version: "3.9"

networks:
  dev:
    external: true

services:
  project_name-adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: "${APP_NAME}-db"
    ports:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.a${APP_NAME}.entrypoints=http"
      - "traefik.http.routers.a${APP_NAME}.rule=Host(`adminer.${APP_NAME}.localhost`)"
    networks:
      - dev
    command: [ "php", "-d", "upload_max_filesize = 10G", "-d", "post_max_size = 10G", "-S", "[::]:8080", "-t", "/var/www/html" ]

  project_name-db:
    image: mariadb:10.11.3
    depends_on:
      - project_name-adminer
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./docker/db_init:/docker-entrypoint-initdb.d:ro
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - dev
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  project_name-tnt-db:
    container_name: project_name-tnt-db
    build: https://github.com/TallieuTallieu/dry-docker.git#tnt-mysql
    environment:
      REMOTE_USER: ${PROD_SERVER_USER}
      REMOTE_HOST: ${PROD_SERVER_IP}
    volumes:
      - ~/.ssh:/root/.ssh:ro
    ports:
      - '3306'
    networks:
      - dev

  project_name-center:
    build: ../center
    hostname: docker_center
    depends_on:
      - project_name-db
    volumes:
      - ../center:/var/www/html
      - ../dry:/var/www/dry
      - ../center/docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ../center/docker/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
      - ../center/docker/xdebug/log:/tmp/xdebug
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.c${APP_NAME}.entrypoints=http"
      - "traefik.http.routers.c${APP_NAME}.rule=Host(`center.${APP_NAME}.localhost`)"
    networks:
      - dev
    environment:
      - CENTER_HTTP_HOST=center.${APP_NAME}.localhost
      - CENTER_DB_HOST=${APP_NAME}-db
      - CENTER_DB_USERNAME=${APP_DB_USERNAME}
      - CENTER_DB_PASSWORD=${APP_DB_PASSWORD}
      - CENTER_DB_NAME=dry

  project_name-site:
    build: https://github.com/TallieuTallieu/dry-docker.git
    hostname: docker_app
    depends_on:
      - project_name-db
      - project_name-center
    volumes:
      - .:/var/www/html
      - ../dry:/var/www/dry
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
      - ./docker/xdebug/log:/tmp/xdebug
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "80"
    command: ["sh", "-c", "eval `ssh-agent -s` && ssh-add && composer install && apache2ctl -D FOREGROUND"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`)"
    networks:
      - dev
